[general]
email = ""

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = true
fastReruns = true

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

